base:
  train_dir: data/output.txt
  checkpoint_dir: checkpoints
  evaluation_dir: outputs
  log_dir: tb_logs
  plot_dir: plots

model:
  name: aminoClust
  input_dim: 1024
  num_clusters: 2
  num_epochs: 100
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  latent_dim: 2
  dropout: 0.5